user favorites & uploaded-resources func added
ddlibrary/website pull request #159
Opened 2020-09-29 12:54 UTC by abubaker47

Users should be able to see there favorite and uploaded-resources on there profile. Issue https://github.com/ddlibrary/website/issues/158 Fixed.

2020-09-29 18:02 UTC, uyscuti-wiki requested changes
This looks good. Few comments inline.

2020-09-30 03:49 UTC, uyscuti-wiki commented on resources/views/users/favorites.blade.php
> +                        <td>{{ ++$c }}</td>
`$c` used before being defined.

2020-09-30 03:49 UTC, uyscuti-wiki commented on resources/views/users/uploaded-resources.blade.php
> +                        <td>{{ ++$c }}</td>
`$c` used before being defined.

2020-12-24 17:41 UTC, abubaker47 commented on resources/views/users/favorites.blade.php
> +        <h1>@lang('Users Details for') <strong>{{ $user->username }}</strong></h1>
Thanks for addressing this, I have resolved it.

2020-12-24 17:42 UTC, abubaker47 commented on resources/views/users/favorites.blade.php
> +@endsection
Resolved.

2020-12-24 17:42 UTC, abubaker47 commented on resources/views/users/uploaded-resources.blade.php
> +        <h1>@lang('Users Details for') <strong>{{ $user->username }}</strong></h1>
Resolved.

2020-12-24 17:42 UTC, abubaker47 commented on resources/views/users/uploaded-resources.blade.php
> +@endsection
Resolved.

2020-12-24 17:42 UTC, abubaker47 commented on resources/views/users/user_nav.blade.php
> +</nav>
Resolved.

2020-12-24 17:42 UTC, abubaker47 commented on resources/views/users/favorites.blade.php
> +                        <td>{{ ++$c }}</td>
Resolved.

2020-12-24 17:42 UTC, abubaker47 commented on resources/views/users/uploaded-resources.blade.php
> +                        <td>{{ ++$c }}</td>
Resolved.

2020-12-26 08:50 UTC, merged