DDL instructional videos link added
ddlibrary/website pull request #164
Opened 2020-11-13 18:56 UTC by abubaker47

DDL instructional video for English, Farsi, and Pashto language added, Story weaver sign-in link added on the banner.

2020-11-16 08:16 UTC, uyscuti-wiki requested changes
Thanks Faisal. Looks pretty good, few comments inline and one in Jira.

2021-01-17 07:43 UTC, abubaker47 commented on resources/views/home.blade.php
> +                <a href="{{ route('storyweaver-confirm') }}" target="_blank" title="@lang('StoryWeaver Library')">
Added the $landing_page parameter.

2021-01-17 07:45 UTC, abubaker47 commented on resources/views/layouts/banner.blade.php
> +                    <a href="{{ route('storyweaver-confirm') }}" title="@lang('StoryWeaver Library')"><img src="{{ URL::to(config('constants.ddlmain_s3_file_storage_url').'/public/img/storyweaver-log
Added the `$landing_page` parameter.

2021-01-17 07:45 UTC, abubaker47 commented on resources/lang/fa.json
> +    "Access children's storybooks through Storyweaver, click here": "برای دسترسی به کتاب‌های داستان برای کودکان نشر شده توسط ستوری ویوور، اینجا را کلیک کنید",
Agree, removed the translations

2021-01-17 07:45 UTC, merged